swift build -Xlinker -lz \
-Xswiftc -Iexternal/SwiftBGFX/.build/debug \
-Xlinker -Lexternal/SwiftBGFX/.build/debug \
-Xlinker -lSwiftBGFX \
-Xcc -DCP_USE_CGTYPES=0 \
-Xswiftc -I$ANDROID_NDK_HOME/sources/android/native_app_glue/ \
-Xcc     -I$ANDROID_NDK_HOME/platforms/android-21/arch-arm/usr/include \
-Xswiftc -I$ANDROID_SWIFT_SOURCE/build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation \
-Xswiftc -I$ANDROID_SWIFT_SOURCE/swift-corelibs-foundation \
-Xswiftc -I$ANDROID_SWIFT_SOURCE/swift-corelibs-foundation/closure \
-Xswiftc -target -Xswiftc armv7-none-linux-androideabi \
-Xswiftc -sdk -Xswiftc $ANDROID_NDK_HOME/platforms/android-21/arch-arm \
-Xcc -target -Xcc armv7-none-linux-androideabi \
-Xcc -B -Xcc $ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ \
-Xcc --sysroot=$ANDROID_NDK_HOME/platforms/android-21/arch-arm/ \
-Xlinker -L/usr/local/lib/swift/android/ \
-Xlinker -L$ANDROID_SWIFT_SOURCE/build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation/ \
-Xlinker -L$ANDROID_NDK_HOME/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a \
-Xlinker -L$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/ \
-Xlinker -L$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/lib/armv7-a/ \
-Xlinker -L$ANDROID_LIBICONV/armeabi-v7a \
-Xlinker -lgcc        -Xlinker -lc++    -Xlinker -ldispatch \
-Xlinker -lFoundation -Xlinker -latomic -Xlinker -licui18n  \
-Xlinker -licuuc \
-Xlinker --sysroot=$ANDROID_NDK_HOME/platforms/android-21/arch-arm/ # This does not work for now and requires a hack for clang
